### ISSUE TITLE
Row alignment issue

### ISSUE THREAD

**Issue by mtubesing** [tifv/gs-scroller#1]
Thanks for this solution for embedded sheets!  I'm noticing an issue with row alignment.  I have sheets with a single frozen row and single frozen column.  The row alignment of the frozen column vs the rest of the sheet slowly slips until by about row 40, it's nearly off by half a row.  (screenshot attached for reference)
![8-28-2017 8-30-54 am](https://user-images.githubusercontent.com/1723166/29773398-51622eb0-8bcb-11e7-8b56-847fbd8445c7.png)

**Comment by tifv** [comment]
Thanks! I don't have much time to investigate thoroughly right now, but the problem origin seems clear.

It is likely that the problem appears when row height is not enough to fit row content, and content starts to «stretch» rows. When frozen cells are separated from moving ones, it is possible that in frozen part cells are stretched by their content, and in moving part they remain narrow. (Actually, vice-versa is also possible.) This can sum up to a significant difference. I should fix this eventually…

In the meantime, I suggest fixing height of rows in your spreadsheet. Just increase it until it will be the same for rows with content and without it. For 12pt font I suggest row height of 24 pixels (as opposed to default 21). There will be no visual difference in spreadsheet editor, but it should fix it for scroller. Probably :)

**Comment by mtubesing** [comment]
Thanks for the super-fast response!  Your idea was correct - I have set the row height explicitly to 24 and that has solved the issue.  Thanks again!

**Comment by hoekbrwr** [comment]
by some reason in rendering on an Android phone or tablet the procees is different when on the PC, both Chrome. It looka OK on the desktop and is wrong on the devices where it does not fit. Some rules starts to economise on its own and then you get different row heights for different tables. So be sure the row height is automically  readjusted for both freezed and scrollabel region! That solves the problem of row differences.
